COUNTRY_ALIASES = {
    # --- United States ---
    "usa": "US",
    "u.s.a": "US",
    "u.s.a.": "US",
    "u.s.": "US",
    "us": "US",
    "america": "US",
    "united states": "US",
    "united states of america": "US",
 
    # --- United Kingdom ---
    "uk": "GB",
    "u.k.": "GB",
    "britain": "GB",
    "great britain": "GB",
    "united kingdom": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "northern ireland": "GB",
 
    # --- Middle East ---
    "uae": "AE",
    "u.a.e.": "AE",
    "emirates": "AE",
    "united arab emirates": "AE",
    "saudi arabia": "SA",
    "saudi": "SA",
    "ksa": "SA",
    "qatar": "QA",
    "kuwait": "KW",
    "bahrain": "BH",
    "oman": "OM",
    "jordan": "JO",
    "lebanon": "LB",
    "israel": "IL",
    "iran": "IR",
    "iraq": "IQ",
    "turkey": "TR",
    "turkiye": "TR",
    "türkiye": "TR",
 
    # --- South & Central Asia ---
    "pakistan": "PK",
    "india": "IN",
    "bangladesh": "BD",
    "sri lanka": "LK",
    "nepal": "NP",
    "afghanistan": "AF",
    "maldives": "MV",
    "kazakhstan": "KZ",
    "uzbekistan": "UZ",
 
    # --- East & Southeast Asia ---
    "japan": "JP",
    "china": "CN",
    "prc": "CN",
    "people's republic of china": "CN",
    "hong kong": "HK",
    "taiwan": "TW",
    "south korea": "KR",
    "korea": "KR",
    "republic of korea": "KR",
    "north korea": "KP",
    "mongolia": "MN",
    "singapore": "SG",
    "malaysia": "MY",
    "indonesia": "ID",
    "thailand": "TH",
    "vietnam": "VN",
    "viet nam": "VN",
    "philippines": "PH",
    "cambodia": "KH",
    "myanmar": "MM",
    "burma": "MM",
    "laos": "LA",
    "brunei": "BN",
 
    # --- Oceania ---
    "australia": "AU",
    "new zealand": "NZ",
    "nz": "NZ",
 
    # --- Western Europe ---
    "germany": "DE",
    "deutschland": "DE",
    "france": "FR",
    "italy": "IT",
    "spain": "ES",
    "portugal": "PT",
    "netherlands": "NL",
    "the netherlands": "NL",
    "holland": "NL",
    "belgium": "BE",
    "luxembourg": "LU",
    "switzerland": "CH",
    "austria": "AT",
    "ireland": "IE",
    "malta": "MT",
    "cyprus": "CY",
 
    # --- Northern Europe ---
    "norway": "NO",
    "sweden": "SE",
    "denmark": "DK",
    "finland": "FI",
    "iceland": "IS",
    "estonia": "EE",
    "latvia": "LV",
    "lithuania": "LT",
 
    # --- Eastern & Southern Europe ---
    "russia": "RU",
    "russian federation": "RU",
    "ukraine": "UA",
    "poland": "PL",
    "czech republic": "CZ",
    "czechia": "CZ",
    "slovakia": "SK",
    "slovenia": "SI",
    "hungary": "HU",
    "romania": "RO",
    "bulgaria": "BG",
    "greece": "GR",
    "serbia": "RS",
    "croatia": "HR",
 
    # --- North America & Caribbean ---
    "canada": "CA",
    "mexico": "MX",
    "cuba": "CU",
    "jamaica": "JM",
    "dominican republic": "DO",
    "costa rica": "CR",
    "panama": "PA",
 
    # --- South America ---
    "brazil": "BR",
    "argentina": "AR",
    "chile": "CL",
    "colombia": "CO",
    "peru": "PE",
    "venezuela": "VE",
    "ecuador": "EC",
    "uruguay": "UY",
 
    # --- Africa ---
    "egypt": "EG",
    "south africa": "ZA",
    "nigeria": "NG",
    "kenya": "KE",
    "ethiopia": "ET",
    "ghana": "GH",
    "tanzania": "TZ",
    "uganda": "UG",
    "morocco": "MA",
    "algeria": "DZ",
    "tunisia": "TN",
    "ivory coast": "CI",
    "cote d'ivoire": "CI",
}